Name: drakontech
Version: 2026.05.24
Release: 1
License: Unlicense
Summary: A DRAKON-based IDE that transforms flowcharts into JavaScript, Lua, Perfolenta, OneScript, or Clojure code
URL: undefined

%description
A DRAKON-based IDE that transforms flowcharts into JavaScript, Lua, Perfolenta, OneScript, or Clojure code
%files
/usr/bin/drakontech
/usr/share/applications/drakontech.desktop
/usr/share/drakontech/LICENSE
/usr/share/drakontech/LICENSES.chromium.html
/usr/share/drakontech/chrome-sandbox
/usr/share/drakontech/chrome_100_percent.pak
/usr/share/drakontech/chrome_200_percent.pak
/usr/share/drakontech/chrome_crashpad_handler
/usr/share/drakontech/drakontech
/usr/share/drakontech/icudtl.dat
/usr/share/drakontech/libEGL.so
/usr/share/drakontech/libGLESv2.so
/usr/share/drakontech/libffmpeg.so
/usr/share/drakontech/libvk_swiftshader.so
/usr/share/drakontech/libvulkan.so.1
/usr/share/drakontech/locales/af.pak
/usr/share/drakontech/locales/am.pak
/usr/share/drakontech/locales/ar.pak
/usr/share/drakontech/locales/bg.pak
/usr/share/drakontech/locales/bn.pak
/usr/share/drakontech/locales/ca.pak
/usr/share/drakontech/locales/cs.pak
/usr/share/drakontech/locales/da.pak
/usr/share/drakontech/locales/de.pak
/usr/share/drakontech/locales/el.pak
/usr/share/drakontech/locales/en-GB.pak
/usr/share/drakontech/locales/en-US.pak
/usr/share/drakontech/locales/es-419.pak
/usr/share/drakontech/locales/es.pak
/usr/share/drakontech/locales/et.pak
/usr/share/drakontech/locales/fa.pak
/usr/share/drakontech/locales/fi.pak
/usr/share/drakontech/locales/fil.pak
/usr/share/drakontech/locales/fr.pak
/usr/share/drakontech/locales/gu.pak
/usr/share/drakontech/locales/he.pak
/usr/share/drakontech/locales/hi.pak
/usr/share/drakontech/locales/hr.pak
/usr/share/drakontech/locales/hu.pak
/usr/share/drakontech/locales/id.pak
/usr/share/drakontech/locales/it.pak
/usr/share/drakontech/locales/ja.pak
/usr/share/drakontech/locales/kn.pak
/usr/share/drakontech/locales/ko.pak
/usr/share/drakontech/locales/lt.pak
/usr/share/drakontech/locales/lv.pak
/usr/share/drakontech/locales/ml.pak
/usr/share/drakontech/locales/mr.pak
/usr/share/drakontech/locales/ms.pak
/usr/share/drakontech/locales/nb.pak
/usr/share/drakontech/locales/nl.pak
/usr/share/drakontech/locales/pl.pak
/usr/share/drakontech/locales/pt-BR.pak
/usr/share/drakontech/locales/pt-PT.pak
/usr/share/drakontech/locales/ro.pak
/usr/share/drakontech/locales/ru.pak
/usr/share/drakontech/locales/sk.pak
/usr/share/drakontech/locales/sl.pak
/usr/share/drakontech/locales/sr.pak
/usr/share/drakontech/locales/sv.pak
/usr/share/drakontech/locales/sw.pak
/usr/share/drakontech/locales/ta.pak
/usr/share/drakontech/locales/te.pak
/usr/share/drakontech/locales/th.pak
/usr/share/drakontech/locales/tr.pak
/usr/share/drakontech/locales/uk.pak
/usr/share/drakontech/locales/ur.pak
/usr/share/drakontech/locales/vi.pak
/usr/share/drakontech/locales/zh-CN.pak
/usr/share/drakontech/locales/zh-TW.pak
/usr/share/drakontech/resources/app/.drakontech/opened.txt
/usr/share/drakontech/resources/app/build_deb.js
/usr/share/drakontech/resources/app/build_rpm.js
/usr/share/drakontech/resources/app/config.json
/usr/share/drakontech/resources/app/drakontech.html
/usr/share/drakontech/resources/app/drakosha.ico
/usr/share/drakontech/resources/app/drakosha.png
/usr/share/drakontech/resources/app/entitlements.mac.plist
/usr/share/drakontech/resources/app/filetree.js
/usr/share/drakontech/resources/app/forge.config.js
/usr/share/drakontech/resources/app/icon.icns
/usr/share/drakontech/resources/app/index.html
/usr/share/drakontech/resources/app/main.js
/usr/share/drakontech/resources/app/package-lock.json
/usr/share/drakontech/resources/app/package.json
/usr/share/drakontech/resources/app/static/Behaviour.drn
/usr/share/drakontech/resources/app/static/Behaviour.js
/usr/share/drakontech/resources/app/static/CallTrace.drn
/usr/share/drakontech/resources/app/static/CallTrace.js
/usr/share/drakontech/resources/app/static/Canvas.js
/usr/share/drakontech/resources/app/static/Config.js
/usr/share/drakontech/resources/app/static/ContextMenu.drn
/usr/share/drakontech/resources/app/static/ContextMenu.js
/usr/share/drakontech/resources/app/static/DTools.js
/usr/share/drakontech/resources/app/static/DraWidgets.js
/usr/share/drakontech/resources/app/static/EditorCtrl.js
/usr/share/drakontech/resources/app/static/HtmlUtils.js
/usr/share/drakontech/resources/app/static/Ide3.js
/usr/share/drakontech/resources/app/static/Ide3Logic.js
/usr/share/drakontech/resources/app/static/InputBox.js
/usr/share/drakontech/resources/app/static/Lomma.drn
/usr/share/drakontech/resources/app/static/Lomma.js
/usr/share/drakontech/resources/app/static/Main.drn
/usr/share/drakontech/resources/app/static/Main.js
/usr/share/drakontech/resources/app/static/Main2.drn
/usr/share/drakontech/resources/app/static/Main2.js
/usr/share/drakontech/resources/app/static/MsgBox.js
/usr/share/drakontech/resources/app/static/Multitouch.drn
/usr/share/drakontech/resources/app/static/Multitouch.js
/usr/share/drakontech/resources/app/static/Nav.js
/usr/share/drakontech/resources/app/static/Popup.js
/usr/share/drakontech/resources/app/static/TabGen4.js
/usr/share/drakontech/resources/app/static/Theme.drn
/usr/share/drakontech/resources/app/static/Theme.js
/usr/share/drakontech/resources/app/static/ToolTip.js
/usr/share/drakontech/resources/app/static/Utils.drn
/usr/share/drakontech/resources/app/static/Utils.js
/usr/share/drakontech/resources/app/static/ViewWidget.drn
/usr/share/drakontech/resources/app/static/ViewWidget.js
/usr/share/drakontech/resources/app/static/appedit.js
/usr/share/drakontech/resources/app/static/common.css
/usr/share/drakontech/resources/app/static/ctest.html
/usr/share/drakontech/resources/app/static/drakosha-1024.png
/usr/share/drakontech/resources/app/static/drakosha132.png
/usr/share/drakontech/resources/app/static/earth2.png
/usr/share/drakontech/resources/app/static/favicon.ico
/usr/share/drakontech/resources/app/static/favicon.png
/usr/share/drakontech/resources/app/static/favicon.xcf
/usr/share/drakontech/resources/app/static/fonts/Arimo-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/Arimo-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/Arimo-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Arimo-BoldItalic.ttf
/usr/share/drakontech/resources/app/static/fonts/Arimo-BoldItalic.woff
/usr/share/drakontech/resources/app/static/fonts/Arimo-BoldItalic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Arimo-Italic.ttf
/usr/share/drakontech/resources/app/static/fonts/Arimo-Italic.woff
/usr/share/drakontech/resources/app/static/fonts/Arimo-Italic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Arimo-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/Arimo-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/Arimo-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Cousine-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/Cousine-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/Cousine-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Bold.woff2
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-BoldItalic.ttf
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-BoldItalic.woff
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-BoldItalic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-BoldItalic.woff2
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Italic.ttf
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Italic.woff
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Italic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Italic.woff2
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/LiberationSans-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/LiberationSans.ttf
/usr/share/drakontech/resources/app/static/fonts/LiberationSans.woff
/usr/share/drakontech/resources/app/static/fonts/LiberationSans.woff.b64
/usr/share/drakontech/resources/app/static/fonts/LiberationSans.woff2
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-BoldItalic.ttf
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-BoldItalic.woff
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-BoldItalic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Italic.ttf
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Italic.woff
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Italic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/RobotoCondensed-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-BoldItalic.ttf
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-BoldItalic.woff
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-BoldItalic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Italic.ttf
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Italic.woff
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Italic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/RobotoMono-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/SourceCodePro-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/SourceCodePro-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/SourceCodePro-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/SourceCodePro-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/SourceCodePro-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/SourceCodePro-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-BoldItalic.ttf
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-BoldItalic.woff
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-BoldItalic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Italic.ttf
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Italic.woff
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Italic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/SourceSansPro-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Tinos-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/Tinos-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/Tinos-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Tinos-BoldItalic.ttf
/usr/share/drakontech/resources/app/static/fonts/Tinos-BoldItalic.woff
/usr/share/drakontech/resources/app/static/fonts/Tinos-BoldItalic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Tinos-Italic.ttf
/usr/share/drakontech/resources/app/static/fonts/Tinos-Italic.woff
/usr/share/drakontech/resources/app/static/fonts/Tinos-Italic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Tinos-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/Tinos-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/Tinos-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-BoldItalic.ttf
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-BoldItalic.woff
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-BoldItalic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Italic.ttf
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Italic.woff
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Italic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/Ubuntu-Regular.woff.b64
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Bold.ttf
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Bold.woff
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Bold.woff.b64
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-BoldItalic.ttf
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-BoldItalic.woff
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-BoldItalic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Italic.ttf
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Italic.woff
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Italic.woff.b64
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Regular.ttf
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Regular.woff
/usr/share/drakontech/resources/app/static/fonts/UbuntuMono-Regular.woff.b64
/usr/share/drakontech/resources/app/static/highlight.js
/usr/share/drakontech/resources/app/static/images/2x.png
/usr/share/drakontech/resources/app/static/images/4-way-pan.png
/usr/share/drakontech/resources/app/static/images/action.png
/usr/share/drakontech/resources/app/static/images/align-center.png
/usr/share/drakontech/resources/app/static/images/align-left.png
/usr/share/drakontech/resources/app/static/images/align-right.png
/usr/share/drakontech/resources/app/static/images/app-icon.png
/usr/share/drakontech/resources/app/static/images/arrow-left.png
/usr/share/drakontech/resources/app/static/images/arrow-right.png
/usr/share/drakontech/resources/app/static/images/arrow-up.png
/usr/share/drakontech/resources/app/static/images/arrow.png
/usr/share/drakontech/resources/app/static/images/backspace.png
/usr/share/drakontech/resources/app/static/images/bold.png
/usr/share/drakontech/resources/app/static/images/branch.png
/usr/share/drakontech/resources/app/static/images/branding-menu-104.png
/usr/share/drakontech/resources/app/static/images/build.png
/usr/share/drakontech/resources/app/static/images/build2.png
/usr/share/drakontech/resources/app/static/images/callout.png
/usr/share/drakontech/resources/app/static/images/cap-arrow-left.png
/usr/share/drakontech/resources/app/static/images/cap-arrow-right.png
/usr/share/drakontech/resources/app/static/images/cap-paw-left.png
/usr/share/drakontech/resources/app/static/images/cap-paw-right.png
/usr/share/drakontech/resources/app/static/images/cap-sarrow-left.png
/usr/share/drakontech/resources/app/static/images/cap-sarrow-right.png
/usr/share/drakontech/resources/app/static/images/cap-solid.png
/usr/share/drakontech/resources/app/static/images/cap-warrow-left.png
/usr/share/drakontech/resources/app/static/images/cap-warrow-right.png
/usr/share/drakontech/resources/app/static/images/case.png
/usr/share/drakontech/resources/app/static/images/check.png
/usr/share/drakontech/resources/app/static/images/check_false.png
/usr/share/drakontech/resources/app/static/images/check_true.png
/usr/share/drakontech/resources/app/static/images/checked.png
/usr/share/drakontech/resources/app/static/images/circle.png
/usr/share/drakontech/resources/app/static/images/class.png
/usr/share/drakontech/resources/app/static/images/close.png
/usr/share/drakontech/resources/app/static/images/close_mac.png
/usr/share/drakontech/resources/app/static/images/cloud.png
/usr/share/drakontech/resources/app/static/images/collapse.png
/usr/share/drakontech/resources/app/static/images/collection.png
/usr/share/drakontech/resources/app/static/images/comment.png
/usr/share/drakontech/resources/app/static/images/copy.png
/usr/share/drakontech/resources/app/static/images/cross.png
/usr/share/drakontech/resources/app/static/images/ctrl-end.png
/usr/share/drakontech/resources/app/static/images/ctrl-start.png
/usr/share/drakontech/resources/app/static/images/dashboard.png
/usr/share/drakontech/resources/app/static/images/db.png
/usr/share/drakontech/resources/app/static/images/delete.png
/usr/share/drakontech/resources/app/static/images/desc.png
/usr/share/drakontech/resources/app/static/images/dots3h.png
/usr/share/drakontech/resources/app/static/images/dots3v.png
/usr/share/drakontech/resources/app/static/images/double-swipe.png
/usr/share/drakontech/resources/app/static/images/down-angle.png
/usr/share/drakontech/resources/app/static/images/dra3.png
/usr/share/drakontech/resources/app/static/images/dra4.png
/usr/share/drakontech/resources/app/static/images/drakosha-loading.png
/usr/share/drakontech/resources/app/static/images/drakosha-logo-text-126.png
/usr/share/drakontech/resources/app/static/images/drakosha-logo-text-504.png
/usr/share/drakontech/resources/app/static/images/drakosha-menu-104.png
/usr/share/drakontech/resources/app/static/images/drakosha104.png
/usr/share/drakontech/resources/app/static/images/drakosha104b.png
/usr/share/drakontech/resources/app/static/images/drakosha98b.png
/usr/share/drakontech/resources/app/static/images/duration.png
/usr/share/drakontech/resources/app/static/images/earth-s.png
/usr/share/drakontech/resources/app/static/images/earth.png
/usr/share/drakontech/resources/app/static/images/end.png
/usr/share/drakontech/resources/app/static/images/error-node.png
/usr/share/drakontech/resources/app/static/images/expand.png
/usr/share/drakontech/resources/app/static/images/export.png
/usr/share/drakontech/resources/app/static/images/f_begin.png
/usr/share/drakontech/resources/app/static/images/f_combo.png
/usr/share/drakontech/resources/app/static/images/f_cross.png
/usr/share/drakontech/resources/app/static/images/f_insertion.png
/usr/share/drakontech/resources/app/static/images/f_menu.png
/usr/share/drakontech/resources/app/static/images/f_shelf.png
/usr/share/drakontech/resources/app/static/images/f_tab.png
/usr/share/drakontech/resources/app/static/images/f_ui_hscroll.png
/usr/share/drakontech/resources/app/static/images/f_ui_vscroll.png
/usr/share/drakontech/resources/app/static/images/folder-menu.png
/usr/share/drakontech/resources/app/static/images/folder-s.png
/usr/share/drakontech/resources/app/static/images/folder-s2.png
/usr/share/drakontech/resources/app/static/images/folder-s3.png
/usr/share/drakontech/resources/app/static/images/folder.png
/usr/share/drakontech/resources/app/static/images/folder2.png
/usr/share/drakontech/resources/app/static/images/foreach.png
/usr/share/drakontech/resources/app/static/images/free-s.png
/usr/share/drakontech/resources/app/static/images/grey-cross.png
/usr/share/drakontech/resources/app/static/images/group-duration-r.png
/usr/share/drakontech/resources/app/static/images/group-duration.png
/usr/share/drakontech/resources/app/static/images/help.png
/usr/share/drakontech/resources/app/static/images/hide-left.png
/usr/share/drakontech/resources/app/static/images/home.png
/usr/share/drakontech/resources/app/static/images/horver.png
/usr/share/drakontech/resources/app/static/images/human.png
/usr/share/drakontech/resources/app/static/images/input.png
/usr/share/drakontech/resources/app/static/images/insertion.png
/usr/share/drakontech/resources/app/static/images/italics.png
/usr/share/drakontech/resources/app/static/images/item-pointer.png
/usr/share/drakontech/resources/app/static/images/left-angle.png
/usr/share/drakontech/resources/app/static/images/left-angle2.png
/usr/share/drakontech/resources/app/static/images/line.png
/usr/share/drakontech/resources/app/static/images/link-s.png
/usr/share/drakontech/resources/app/static/images/list-algoprop.png
/usr/share/drakontech/resources/app/static/images/list-drakon.png
/usr/share/drakontech/resources/app/static/images/list-drakon2-exp.png
/usr/share/drakontech/resources/app/static/images/list-drakon2.png
/usr/share/drakontech/resources/app/static/images/list-free.png
/usr/share/drakontech/resources/app/static/images/list-mind.png
/usr/share/drakontech/resources/app/static/images/list-pj.png
/usr/share/drakontech/resources/app/static/images/list-scen.png
/usr/share/drakontech/resources/app/static/images/list-tx.png
/usr/share/drakontech/resources/app/static/images/logo-drakon.png
/usr/share/drakontech/resources/app/static/images/logo-free.png
/usr/share/drakontech/resources/app/static/images/logo-graf.png
/usr/share/drakontech/resources/app/static/images/ls-solid.png
/usr/share/drakontech/resources/app/static/images/ls-style-1.png
/usr/share/drakontech/resources/app/static/images/ls-style-2.png
/usr/share/drakontech/resources/app/static/images/ls-style-3.png
/usr/share/drakontech/resources/app/static/images/ls-style-4.png
/usr/share/drakontech/resources/app/static/images/many-copy.png
/usr/share/drakontech/resources/app/static/images/many-move.png
/usr/share/drakontech/resources/app/static/images/menu.png
/usr/share/drakontech/resources/app/static/images/middle-mouse.png
/usr/share/drakontech/resources/app/static/images/mind-down.png
/usr/share/drakontech/resources/app/static/images/mind-hor.png
/usr/share/drakontech/resources/app/static/images/mind-left.png
/usr/share/drakontech/resources/app/static/images/mind-right.png
/usr/share/drakontech/resources/app/static/images/mind-s.png
/usr/share/drakontech/resources/app/static/images/mind-up.png
/usr/share/drakontech/resources/app/static/images/mind-ver.png
/usr/share/drakontech/resources/app/static/images/mind-ver2.png
/usr/share/drakontech/resources/app/static/images/module.png
/usr/share/drakontech/resources/app/static/images/no-color.png
/usr/share/drakontech/resources/app/static/images/normal-mode.png
/usr/share/drakontech/resources/app/static/images/notebook.png
/usr/share/drakontech/resources/app/static/images/output.png
/usr/share/drakontech/resources/app/static/images/par.png
/usr/share/drakontech/resources/app/static/images/params-1.png
/usr/share/drakontech/resources/app/static/images/parblock.png
/usr/share/drakontech/resources/app/static/images/pause.png
/usr/share/drakontech/resources/app/static/images/pay-s.png
/usr/share/drakontech/resources/app/static/images/pc.png
/usr/share/drakontech/resources/app/static/images/phone.png
/usr/share/drakontech/resources/app/static/images/picture-s.png
/usr/share/drakontech/resources/app/static/images/placeholder.png
/usr/share/drakontech/resources/app/static/images/plus-collapse.png
/usr/share/drakontech/resources/app/static/images/plus-expand.png
/usr/share/drakontech/resources/app/static/images/plus-expande.png
/usr/share/drakontech/resources/app/static/images/plus.png
/usr/share/drakontech/resources/app/static/images/portrait.png
/usr/share/drakontech/resources/app/static/images/primitive.png
/usr/share/drakontech/resources/app/static/images/process.png
/usr/share/drakontech/resources/app/static/images/ptr-left.png
/usr/share/drakontech/resources/app/static/images/ptr-right.png
/usr/share/drakontech/resources/app/static/images/qsearch.png
/usr/share/drakontech/resources/app/static/images/question.png
/usr/share/drakontech/resources/app/static/images/radio_false.png
/usr/share/drakontech/resources/app/static/images/radio_true.png
/usr/share/drakontech/resources/app/static/images/recent-s.png
/usr/share/drakontech/resources/app/static/images/record.png
/usr/share/drakontech/resources/app/static/images/rectangle.png
/usr/share/drakontech/resources/app/static/images/redo.png
/usr/share/drakontech/resources/app/static/images/right-angle.png
/usr/share/drakontech/resources/app/static/images/right-angle2.png
/usr/share/drakontech/resources/app/static/images/rounded.png
/usr/share/drakontech/resources/app/static/images/search-s.png
/usr/share/drakontech/resources/app/static/images/search.png
/usr/share/drakontech/resources/app/static/images/select-mode.png
/usr/share/drakontech/resources/app/static/images/select.png
/usr/share/drakontech/resources/app/static/images/server1.png
/usr/share/drakontech/resources/app/static/images/server2.png
/usr/share/drakontech/resources/app/static/images/settings.png
/usr/share/drakontech/resources/app/static/images/share.png
/usr/share/drakontech/resources/app/static/images/shelf.png
/usr/share/drakontech/resources/app/static/images/show-right.png
/usr/share/drakontech/resources/app/static/images/show-toobox.png
/usr/share/drakontech/resources/app/static/images/silhouette.png
/usr/share/drakontech/resources/app/static/images/sinput.png
/usr/share/drakontech/resources/app/static/images/soutput.png
/usr/share/drakontech/resources/app/static/images/style.png
/usr/share/drakontech/resources/app/static/images/tablet.png
/usr/share/drakontech/resources/app/static/images/text.png
/usr/share/drakontech/resources/app/static/images/theme-icon-black.png
/usr/share/drakontech/resources/app/static/images/theme-icon-blue.png
/usr/share/drakontech/resources/app/static/images/theme-icon-blue2.png
/usr/share/drakontech/resources/app/static/images/theme-icon-bluenight.png
/usr/share/drakontech/resources/app/static/images/theme-icon-class.png
/usr/share/drakontech/resources/app/static/images/theme-icon-cloud.png
/usr/share/drakontech/resources/app/static/images/theme-icon-dark.png
/usr/share/drakontech/resources/app/static/images/theme-icon-girl.png
/usr/share/drakontech/resources/app/static/images/theme-icon-greenblue.png
/usr/share/drakontech/resources/app/static/images/theme-icon-greenyellow.png
/usr/share/drakontech/resources/app/static/images/theme-icon-lagoona.png
/usr/share/drakontech/resources/app/static/images/theme-icon-monogreen.png
/usr/share/drakontech/resources/app/static/images/theme-icon-mut.png
/usr/share/drakontech/resources/app/static/images/theme-icon-nechu.png
/usr/share/drakontech/resources/app/static/images/theme-icon-night.png
/usr/share/drakontech/resources/app/static/images/theme-icon-parr.png
/usr/share/drakontech/resources/app/static/images/theme-icon-past.png
/usr/share/drakontech/resources/app/static/images/theme-icon-pastred.png
/usr/share/drakontech/resources/app/static/images/theme-icon-white.png
/usr/share/drakontech/resources/app/static/images/theme-icon-wnight.png
/usr/share/drakontech/resources/app/static/images/theme.png
/usr/share/drakontech/resources/app/static/images/theme11.png
/usr/share/drakontech/resources/app/static/images/theme12.png
/usr/share/drakontech/resources/app/static/images/theme13.png
/usr/share/drakontech/resources/app/static/images/theme14.png
/usr/share/drakontech/resources/app/static/images/theme21.png
/usr/share/drakontech/resources/app/static/images/theme22.png
/usr/share/drakontech/resources/app/static/images/theme23.png
/usr/share/drakontech/resources/app/static/images/theme24.png
/usr/share/drakontech/resources/app/static/images/theme31.png
/usr/share/drakontech/resources/app/static/images/theme32.png
/usr/share/drakontech/resources/app/static/images/theme33.png
/usr/share/drakontech/resources/app/static/images/theme34.png
/usr/share/drakontech/resources/app/static/images/theme41.png
/usr/share/drakontech/resources/app/static/images/theme42.png
/usr/share/drakontech/resources/app/static/images/theme43.png
/usr/share/drakontech/resources/app/static/images/theme44.png
/usr/share/drakontech/resources/app/static/images/theme51.png
/usr/share/drakontech/resources/app/static/images/theme52.png
/usr/share/drakontech/resources/app/static/images/theme53.png
/usr/share/drakontech/resources/app/static/images/theme54.png
/usr/share/drakontech/resources/app/static/images/theme61.png
/usr/share/drakontech/resources/app/static/images/theme62.png
/usr/share/drakontech/resources/app/static/images/theme63.png
/usr/share/drakontech/resources/app/static/images/theme64.png
/usr/share/drakontech/resources/app/static/images/theme71.png
/usr/share/drakontech/resources/app/static/images/theme72.png
/usr/share/drakontech/resources/app/static/images/theme73.png
/usr/share/drakontech/resources/app/static/images/theme74.png
/usr/share/drakontech/resources/app/static/images/thickness.png
/usr/share/drakontech/resources/app/static/images/timer.png
/usr/share/drakontech/resources/app/static/images/to-primitive-s.png
/usr/share/drakontech/resources/app/static/images/to-primitive-s2.png
/usr/share/drakontech/resources/app/static/images/to-primitive.png
/usr/share/drakontech/resources/app/static/images/trash-s.png
/usr/share/drakontech/resources/app/static/images/trash-s2.png
/usr/share/drakontech/resources/app/static/images/trash.png
/usr/share/drakontech/resources/app/static/images/tri-down.png
/usr/share/drakontech/resources/app/static/images/type-drakon.png
/usr/share/drakontech/resources/app/static/images/type-free.png
/usr/share/drakontech/resources/app/static/images/unchecked.png
/usr/share/drakontech/resources/app/static/images/undo.png
/usr/share/drakontech/resources/app/static/images/up-angle.png
/usr/share/drakontech/resources/app/static/images/user-s.png
/usr/share/drakontech/resources/app/static/images/user.png
/usr/share/drakontech/resources/app/static/images/user2.png
/usr/share/drakontech/resources/app/static/images/video-s.png
/usr/share/drakontech/resources/app/static/images/workspace-s.png
/usr/share/drakontech/resources/app/static/images/workspace-s2.png
/usr/share/drakontech/resources/app/static/images/workspace.png
/usr/share/drakontech/resources/app/static/images/zoom.png
/usr/share/drakontech/resources/app/static/js/build.js
/usr/share/drakontech/resources/app/static/js/clojurelexer.js
/usr/share/drakontech/resources/app/static/js/electron.js
/usr/share/drakontech/resources/app/static/js/frontendmain.js
/usr/share/drakontech/resources/app/static/js/local.js
/usr/share/drakontech/resources/app/static/js/preload.js
/usr/share/drakontech/resources/app/static/js/project.js
/usr/share/drakontech/resources/app/static/js/projectimporter.js
/usr/share/drakontech/resources/app/static/js/strings.js
/usr/share/drakontech/resources/app/static/libs/base16-dark.css
/usr/share/drakontech/resources/app/static/libs/black.css
/usr/share/drakontech/resources/app/static/libs/canvas2svg.js
/usr/share/drakontech/resources/app/static/libs/clojure.js
/usr/share/drakontech/resources/app/static/libs/cloud.css
/usr/share/drakontech/resources/app/static/libs/codemirror.css
/usr/share/drakontech/resources/app/static/libs/codemirror.js
/usr/share/drakontech/resources/app/static/libs/css.js
/usr/share/drakontech/resources/app/static/libs/dark1.css
/usr/share/drakontech/resources/app/static/libs/dark3.css
/usr/share/drakontech/resources/app/static/libs/default.css
/usr/share/drakontech/resources/app/static/libs/drakongen.js
/usr/share/drakontech/resources/app/static/libs/drakontechgen.js
/usr/share/drakontech/resources/app/static/libs/escodegen.browser.min.js
/usr/share/drakontech/resources/app/static/libs/esprima.js
/usr/share/drakontech/resources/app/static/libs/fontfaceobserver.js
/usr/share/drakontech/resources/app/static/libs/htmlembedded.js
/usr/share/drakontech/resources/app/static/libs/htmlmixed.js
/usr/share/drakontech/resources/app/static/libs/javascript.js
/usr/share/drakontech/resources/app/static/libs/lua.js
/usr/share/drakontech/resources/app/static/libs/luaparse.js
/usr/share/drakontech/resources/app/static/libs/mousetrap.js
/usr/share/drakontech/resources/app/static/libs/night.css
/usr/share/drakontech/resources/app/static/libs/night2.css
/usr/share/drakontech/resources/app/static/libs/parrot.css
/usr/share/drakontech/resources/app/static/libs/red.css
/usr/share/drakontech/resources/app/static/libs/strict.css
/usr/share/drakontech/resources/app/static/libs/white1.css
/usr/share/drakontech/resources/app/static/libs/white2.css
/usr/share/drakontech/resources/app/static/libs/xml.js
/usr/share/drakontech/resources/app/static/libs/zed.css
/usr/share/drakontech/resources/app/static/loader.js
/usr/share/drakontech/resources/app/static/loading.css
/usr/share/drakontech/resources/app/static/logo-text-img-s-2.png
/usr/share/drakontech/resources/app/static/logo-text-img-s-hub.png
/usr/share/drakontech/resources/app/static/logo-text-s-hub.png
/usr/share/drakontech/resources/app/static/quill.snow.css
/usr/share/drakontech/resources/app/static/quill2.min.js
/usr/share/drakontech/resources/app/static/red-cross.png
/usr/share/drakontech/resources/app/static/red-menu.png
/usr/share/drakontech/resources/app/static/reset.css
/usr/share/drakontech/resources/app/static/style.css
/usr/share/drakontech/resources/app/static/styles/main.css
/usr/share/drakontech/resources.pak
/usr/share/drakontech/snapshot_blob.bin
/usr/share/drakontech/v8_context_snapshot.bin
/usr/share/drakontech/version
/usr/share/drakontech/vk_swiftshader_icd.json
